### PR TITLE
allow to confiure persist ip pool

### LINKED ISSUE #4: allow persist ip pool configuration
Allow to configure:

ifconfig-pool-persist

Think a boolean should be enough?

### PR DESCRIPTION
**Pull request by toepi**
fixes #4

### CODE REVIEW

**Comment by inkblot** [comment]
I like this change. Have you used it? Does it work as expected?

Also, there are conflicts that must be resolved before it can be merged.

**Comment by toepi** [comment]
I use this parameter at my current setup (not puppet managed). For this modules change I only test if openvpn starts - and it does ...

**Comment by inkblot** [comment]
Thanks for the PR!

**Comment by inkblot** [comment]
This change is included in version 0.6.0 of the module on the Puppet Forge.

**Pull request merged**
